# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
moonwave-extractor = "evaera/moonwave@1.1.3"
wally = "UpliftGames/wally@0.3.2"
stylua = "JohnnyMorganz/stylua@0.20.0"
