[package]
name = "duckymomo360/comedygame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Fusion = "elttob/fusion@0.2.0"
TestEZ = "roblox/testez@0.4.1"
